services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: autorepairshop-sql
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - autorepairshop-sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '>/dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 15

volumes:
  autorepairshop-sql-data: