apiVersion: v1
kind: Service # Responsável por expor Pods e balancear tráfego entre eles.
metadata:
  name: api
  namespace: oficina # Service chamado api dentro do namespace oficina
spec:
  type: ClusterIP # Tipo do service acessível somente dentro do cluster
  selector:
    app: api # Service seleciona todos os Pods que possuem o label app=api
  ports:
    - port: 80
      targetPort: 8080
