apiVersion: v1
kind: Secret # Armazenamento de configurações/infos sensíveis
metadata:
  name: api-secrets # Nome da Secret
  namespace: oficina # Namespace em que está sendo criada
type: Opaque # Tipo genérico de sectet utilizado como chave/valor
stringData:
  Jwt__Key: "MinhaChaveSuperSecretaComMaisDe256Bits12345678901234567890"
  Jwt__Issuer: "AutoRepairShop"
  Jwt__Audience: "AutoRepairShopUsers"
  Jwt__ExpiresInMinutes: "60"