apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler # Cria um HPA, responsável por aumentar ou diminuir Pods automaticamente com base em métricas
metadata:
  name: api-hpa # HPA chamado api-hpa dentro do namespace oficina
  namespace: oficina
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment # Esse HPA "controla" o deployment api
    name: api
  minReplicas: 1 # Limites de escala
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu # HPA vai usar CPU como critério de escala
        target:
          type: Utilization
          averageUtilization: 50 